version: "3.9"

services:
  backend:
    image: ghcr.io/piotrbelda/ner:${TAG-default}
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:5000:5000"
    command: poetry run python main.py
    stdin_open: true
    tty: true