name: Test CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Build backend image
        run: docker-compose build backend
      - name: Code linting
        run: docker-compose run --rm backend bash lint.sh